notebook to test DeepIRES's performance

In [15]:
from sklearn.metrics import roc_auc_score, average_precision_score, f1_score,accuracy_score,recall_score,matthews_corrcoef,confusion_matrix,roc_curve, precision_recall_curve
import numpy as np
import pandas as pd
import os
from sklearn.metrics import auc
import keras.backend as k
from scipy import stats
from model import deepires_model
#忽略
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import matplotlib.pyplot as plt
import tensorflow as tf

In [16]:
def plotROC(test,score):
    fpr,tpr,threshold = roc_curve(test, score)
    auc_roc = roc_auc_score(test, score)
    plt.figure()
    font = {'family': 'Times New Roman',
         'weight': 'normal',
         'size': 22,
         }
    lw = 3
    plt.figure(figsize=(8,8))
    plt.plot(fpr, tpr, color='darkorange',lw=lw, label='auROC = %f' %auc_roc)

    plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
    plt.xlim([-0.01, 1.01])
    plt.ylim([-0.01, 1.01])
    plt.tick_params(labelsize=20)
    plt.xlabel('False Positive Rate',font)
    plt.ylabel('True Positive Rate',font)
    plt.title('Receiver operating characteristic curve',font)
    plt.legend(loc="lower right")
    plt.savefig('x.jpg',dpi=350)
    plt.show()

In [17]:
test = np.load('../dataset/test/balanced_test_set.npz')
#test=np.load('C:/Users/czw20/Desktop/python/linear/iresite.npz')
X_tes,y_tes = test['X_tes'], test['y_tes']
model=deepires_model()
# weight_path='../weights/new/' (original weight path)
weight_path = '../weights/first'
model.load_weights(weight_path).expect_partial()
y_pred_1 = model.predict(X_tes)

print("done predicting")

y_pred=np.where(y_pred_1>0.5,1,0)
acc = accuracy_score(y_tes, y_pred)
sn = recall_score(y_tes, y_pred)
mcc = matthews_corrcoef(y_tes, y_pred)
tn, fp, fn, tp = confusion_matrix(y_tes, y_pred).ravel()
sp = tn / (tn + fp)
auroc = roc_auc_score(y_tes, y_pred_1)
f1 = f1_score(y_tes, y_pred.reshape(-1))
lr_precision, lr_recall, _ = precision_recall_curve(y_tes, y_pred_1)
aupr=auc(lr_recall,lr_precision)

print("ACC : ", acc)
print("SN : ", sn)
print("SP : ", sp)
print("MCC : ", mcc)
print("AUC : ", auroc)
print("F1-sorce : ", f1)
print("AUPR : ", aupr)

12/12 [==============================] - 1s 12ms/step
done predicting
ACC :  0.7671957671957672
SN :  0.7248677248677249
SP :  0.8095238095238095
MCC :  0.5363167880704651
AUC :  0.8671929677220683
F1-sorce :  0.7569060773480663
AUPR :  0.8857785560053044


In [25]:
# save the numpy predictions to an npz file
print(type(y_pred))

np.savez("../predictions/y_pred_test.npz", y_pred=y_pred)



<class 'numpy.ndarray'>


In [19]:
test = np.load('../dataset/test/balanced_test_set.npz')


In [20]:
for file in test.files:
    print(file)

X_tes
y_tes


In [21]:
print(test['y_tes'][:10])

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [22]:
print(test['X_tes'][:10])

[[4 2 4 ... 1 4 3]
 [3 2 4 ... 2 4 3]
 [1 3 1 ... 1 1 1]
 ...
 [3 2 1 ... 3 1 2]
 [2 2 4 ... 3 3 3]
 [1 2 4 ... 3 4 4]]


In [23]:
# seaborn needs python versions 3.8+, while DeepIRES was developed in python 3.7
# save the 
